# Generated by Django 5.0.3 on 2024-04-03 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=10, max_digits=25)),
                ('lon', models.DecimalField(decimal_places=10, max_digits=25)),
                ('User_ID', models.CharField()),
                ('Num_Adults', models.SmallIntegerField()),
                ('Num_Calf', models.SmallIntegerField()),
                ('Activity', models.CharField()),
                ('Comments', models.TextField(null=True)),
                ('Sighting_date', models.DateTimeField()),
                ('Created_date', models.DateTimeField()),
                ('Image', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
