# Generated by Django 5.0.3 on 2024-04-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting_data',
            name='Activity',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='sighting_data',
            name='Num_Adults',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='sighting_data',
            name='Num_Calf',
            field=models.SmallIntegerField(null=True),
        ),
    ]
