# Generated by Django 5.0.3 on 2024-04-04 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0003_alter_sighting_data_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting_data',
            name='Image',
            field=models.CharField(null=True),
        ),
    ]
