# Generated by Django 5.0.3 on 2024-04-10 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0004_alter_sighting_data_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting_data',
            name='Image',
            field=models.TextField(null=True),
        ),
    ]
