# Generated by Django 5.0.3 on 2024-04-12 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0005_alter_sighting_data_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting_data',
            name='Activity',
            field=models.CharField(default='Swimming'),
        ),
        migrations.AlterField(
            model_name='sighting_data',
            name='Created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sighting_data',
            name='Num_Adults',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sighting_data',
            name='Num_Calf',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sighting_data',
            name='User_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sightings', to=settings.AUTH_USER_MODEL),
        ),
    ]
