# Generated by Django 5.0.3 on 2024-04-12 00:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0007_sighting_data_user_alter_sighting_data_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sighting_data',
            old_name='Activity',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='sighting_data',
            old_name='Comments',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='sighting_data',
            old_name='Sighting_date',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='sighting_data',
            old_name='User_ID',
            new_name='data_source',
        ),
        migrations.RenameField(
            model_name='sighting_data',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='sighting_data',
            old_name='Num_Adults',
            new_name='num_Adults',
        ),
        migrations.RenameField(
            model_name='sighting_data',
            old_name='Num_Calf',
            new_name='num_Calf',
        ),
        migrations.RemoveField(
            model_name='sighting_data',
            name='Created_date',
        ),
        migrations.AddField(
            model_name='sighting_data',
            name='sighting_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
