# Generated by Django 5.0.3 on 2024-04-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0011_alter_sighting_data_lat_alter_sighting_data_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting_data',
            name='image',
            field=models.TextField(default='No Image'),
            preserve_default=False,
        ),
    ]
