# Generated by Django 5.0.3 on 2024-04-12 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0012_alter_sighting_data_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting_data',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
