# Generated by Django 5.0.3 on 2024-04-13 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0014_alter_sighting_data_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting_data',
            name='comments',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
