# Generated by Django 5.0.3 on 2024-04-15 16:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactions_app', '0002_rename_comments_reactions_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reactions',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
