
services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  backend:
    build:
      context: .
      dockerfile: ./backend/docker/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/manateewatch/backend
    depends_on:
      - db
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
  frontend:
    build: 
      context: .
      dockerfile: ./frontend/manatee-watch/docker/development/Dockerfile
    container_name: React
    ports:
      - 3000:3000
    volumes:
      - ./frontend/manatee-watch/:/manateewatch/frontend/manatee-watch
    depends_on:
      - backend
  

volumes:
  postgres_data:
