
services:
  nginx:
    image: nginx:alpine
    build: 
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/manateewatch-nginx.conf:/etc/nginx/conf.d/manateewatch-nginx.conf:ro
      - ./nginx/ssl_cert.pem:/etc/nginx/ssl/ssl_cert.pem:ro
      - ./nginx/ssl_cert_key.key:/etc/nginx/ssl/ssl_cert_key.key:ro
    ports:
      - 80:80
    restart: always
    depends_on:
      - frontend
      - backend
  frontend:
    restart: unless-stopped
    build: 
      context: .
      dockerfile: ./frontend/docker/production/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: ./backend/docker/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/manateewatch/backend
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env

networks:
  manateewatch-network:
    driver: bridge