
services:
  nginx:
    image: kdwwatts/manateewatch-nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/manateewatch-nginx.conf:/etc/nginx/conf.d/manateewatch-nginx.conf:ro
      - ./nginx/ssl_cert.pem:/etc/nginx/ssl/ssl_cert.pem:ro
      - ./nginx/ssl_cert_key.key:/etc/nginx/ssl/ssl_cert_key.key:ro
    ports:
      - 80:80
      - 443:443
    restart: always
    depends_on:
      - frontend
      - backend
    networks:
      - manateewatch-network
  frontend:
    restart: unless-stopped
    image: kdwwatts/manateewatch-fe:latest
    ports:
      - 3000:3000
    depends_on:
      - backend
    networks:
      - manateewatch-network
  backend:
    image: kdwwatts/manateewatch-be:latest
    command: gunicorn manateewatch_proj.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - ./backend/.env
    networks:
      - manateewatch-network
      


networks:
  manateewatch-network:
    driver: bridge