# Generated by Django 4.2.2 on 2025-09-08 17:23

from django.db import migrations
import user_app.managers


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_remove_client_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='client',
            managers=[
                ('objects', user_app.managers.UserManager()),
            ],
        ),
    ]
